"""Interview State — shared schema for the agentic LangGraph interview workflow.

The graph LOOPS: SUPERVISOR → AGENT → WAIT_FOR_ANSWER → EVALUATE → SUPERVISOR → ...
The Supervisor is a genuine reasoning agent that decides dynamically:
  • Which agent to call next (no pre-built turn plan)
  • When to follow up vs. move on
  • When to escalate/de-escalate difficulty
  • When to end the interview (signal-based, not turn-count based)
"""

from typing import TypedDict, Dict, List, Optional, Any


class InterviewState(TypedDict, total=False):
    """Complete state that flows through the agentic interview graph."""

    # ── session context (set once at start, read-only during graph) ───
    session_id: str
    interview_config: Dict[str, Any]   # company, role, experience, difficulty, jd, topics, selected_types, …
    candidate: Dict[str, Any]          # name, resume_parsed, …

    # ── dynamic interview state (mutated by supervisor) ──────────────
    turn_counter: int                  # incremented each time a question is answered (starts 0)
    max_turns: int                     # hard safety cap — the ONLY guardrail
    current_difficulty: str            # mutable: supervisor can escalate/de-escalate
    current_agent: str                 # which agent type is active: "code" | "resume" | "hr"

    # ── coverage & memory ────────────────────────────────────────────
    coverage_context: Dict[str, Any]   # already_asked_topics, avoid_topics, weakness_tags, strength_tags
    turns: List[Dict[str, Any]]        # completed turn history

    # ── supervisor reasoning (the agentic brain) ─────────────────────
    supervisor_scratchpad: List[str]   # chain-of-thought reasoning log — grows each iteration
    signal_confidence: float           # 0.0–1.0: supervisor's confidence it has enough data to assess

    # ── per-turn data ────────────────────────────────────────────────
    current_question_pack: Dict[str, Any]  # the question being asked right now
    answer_text: str                       # candidate's answer (set via interrupt)
    evaluation: Dict[str, Any]             # scores from evaluator

    # ── supervisor output ────────────────────────────────────────────
    supervisor_decision: Dict[str, Any]    # action, next_agent, reasoning, acknowledgement, transition
    next_question_pack: Dict[str, Any]     # generated by the routed agent
    is_interview_over: bool

    # ── final output ─────────────────────────────────────────────────
    final_scores: Optional[Dict[str, Any]]
